name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Lint
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript check
        run: npm run type-check
        working-directory: apps/web
        
      - name: Run linting
        run: npm run lint
        working-directory: apps/web
        
      - name: Run tests (if available)
        run: npm run test --if-present
        working-directory: apps/web

  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: test
    name: Deploy Preview
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=$url" >> $GITHUB_OUTPUT
          
      - name: Test Preview Deployment
        run: |
          sleep 30  # Wait for deployment to be ready
          ./test-deployment.sh ${{ steps.deploy.outputs.preview_url }}

  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    name: Deploy Production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "production_url=$url" >> $GITHUB_OUTPUT
          
      - name: Test Production Deployment
        run: |
          sleep 60  # Wait for deployment to be ready
          ./test-deployment.sh ${{ steps.deploy.outputs.production_url }}
          
      - name: Health Check
        run: |
          curl -f ${{ steps.deploy.outputs.production_url }}/api/health || exit 1
          
      - name: Post-deploy notification
        if: success()
        run: |
          echo "🎉 Production deployment successful!"
          echo "URL: ${{ steps.deploy.outputs.production_url }}"
          
      - name: Rollback on failure
        if: failure()
        run: |
          echo "❌ Deployment failed, manual rollback may be required"
          echo "Check Vercel dashboard for details"